version: "3.8"
services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: nlp-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
