apiVersion: v1
kind: Service
metadata:
  name: nlp-api-service
spec:
  type: NodePort
  selector:
    app: nlp-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30007
